server:
  port: 2020
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sob_blog?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
