server:
  port: 2020
  servlet:
    context-path: /blog

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sob_blog?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    password: 123456
    timeout: 1000

  # Redis服务器连接端口
  # spring.redis.port=6379
  # Redis服务器地址
  # spring.redis.host=127.0.0.1
  # Redis数据库索引（默认为0）
  # spring.redis.database=0
  # Redis服务器连接密码（默认为空）
  # spring.redis.password=
  # 连接池最大连接数（使用负值表示没有限制）
  # spring.redis.jedis.pool.max-active=8
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  # spring.redis.jedis.pool.max-wait=-1ms
  # 连接池中的最大空闲连接
  # spring.redis.jedis.pool.max-idle=8
  # 连接池中的最小空闲连接
  # spring.redis.jedis.pool.min-idle=0
  # 连接超时时间（毫秒）
  # spring.redis.timeout=5000ms

  jpa:
    show-sql: true

blog-config:
  kjcBoot: http://192.168.1.134:8103/ypt

nacos:
  config:
    server-addr: 127.0.0.1:8848
  discovery:
    server-addr: 127.0.0.1:8848

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**Mapper.xml,classpath:mapper/*/*Mapper.xml

schedule:
    enable: false